runtime: nodejs16

env_variables:
  # Tambahkan variabel lingkungan lainnya di sini
  DB_HOST: 34.101.230.214,
  DB_USER: root,
  DB_PASSWORD: password,
  DB_NAME: farmgenius-db

service: default

handlers:
  - url: /.*
    script: auto

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

